# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Qg526ZyYXjV0wfVyNOqGn9o23DCbTef
"""



pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('20240518_174820.jpg')
rasm1=cv2.imread('20240518_174832.jpg')
rasm2=cv2.imread('20241103_163103.jpg')

cv2_imshow(rasm)
cv2_imshow(rasm1)
cv2_imshow(rasm2)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
oqqora1=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
oqqora2=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
cv2_imshow(oqqora1)
cv2_imshow(oqqora2)